project_id = "cqafvdufojdeygaziovh"

[functions.process-referral]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false
